# Generated by Django 4.1.6 on 2023-02-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
