# Generated by Django 4.1.6 on 2023-03-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedapp', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='courses',
            field=models.ManyToManyField(blank=True, to='schedapp.course'),
        ),
    ]
