# Generated by Django 4.1.6 on 2023-04-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedapp', '0005_alter_user_symbiotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Other_Course',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='courses',
            new_name='other_courses',
        ),
    ]
