# Generated by Django 4.1.6 on 2023-04-03 18:15

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedapp', '0006_rename_course_other_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('index', models.CharField(blank=True, max_length=255, null=True)),
                ('crse_id', models.CharField(blank=True, max_length=255, null=True)),
                ('crse_offer_nbr', models.IntegerField(blank=True, null=True)),
                ('strm', models.CharField(blank=True, max_length=255, null=True)),
                ('session_code', models.CharField(blank=True, max_length=255, null=True)),
                ('session_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('class_section', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('location_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('start_dt', models.CharField(blank=True, max_length=255, null=True)),
                ('end_dt', models.CharField(blank=True, max_length=255, null=True)),
                ('class_stat', models.CharField(blank=True, max_length=255, null=True)),
                ('campus', models.CharField(blank=True, max_length=255, null=True)),
                ('campus_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('class_nbr', models.IntegerField(primary_key=True, serialize=False)),
                ('acad_career', models.CharField(blank=True, max_length=255, null=True)),
                ('acad_career_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('component', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('catalog_nbr', models.CharField(blank=True, max_length=255, null=True)),
                ('class_type', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule_print', models.CharField(blank=True, max_length=255, null=True)),
                ('acad_group', models.CharField(blank=True, max_length=255, null=True)),
                ('instruction_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('instruction_mode_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('acad_org', models.CharField(blank=True, max_length=255, null=True)),
                ('wait_tot', models.IntegerField(blank=True, null=True)),
                ('wait_cap', models.IntegerField(blank=True, null=True)),
                ('class_capacity', models.IntegerField(blank=True, null=True)),
                ('enrollment_total', models.IntegerField(blank=True, null=True)),
                ('enrollment_available', models.IntegerField(blank=True, null=True)),
                ('descr', models.TextField()),
                ('rqmnt_designtn', models.CharField(blank=True, max_length=255, null=True)),
                ('units', models.CharField(blank=True, max_length=255, null=True)),
                ('combined_section', models.CharField(blank=True, max_length=255, null=True)),
                ('enrl_stat', models.CharField(blank=True, max_length=255, null=True)),
                ('enrl_stat_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('instructors', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('section_type', models.CharField(blank=True, max_length=255, null=True)),
                ('meetings', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('crse_attr', models.CharField(blank=True, max_length=255, null=True)),
                ('crse_attr_value', models.CharField(blank=True, max_length=255, null=True)),
                ('reserve_caps', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='courses',
            field=models.ManyToManyField(blank=True, to='schedapp.course'),
        ),
    ]
