# Generated by Django 4.1.7 on 2023-04-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedapp', '0007_course_schedule_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='schedapp.course')),
            ],
        ),
    ]
