# Generated by Django 4.1.6 on 2023-04-03 20:41

from django.db import migrations, models
import schedapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedapp', '0008_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='approval_status',
            field=models.CharField(blank=True, choices=[(schedapp.models.ApprovalStatus['UN'], 'unsubmitted'), (schedapp.models.ApprovalStatus['PD'], 'pending'), (schedapp.models.ApprovalStatus['AP'], 'approved')], default=schedapp.models.ApprovalStatus['UN'], max_length=60, null=True),
        ),
    ]
