# Generated by Django 4.1.6 on 2023-04-21 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedapp', '0011_alter_schedule_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('unsubmitted', 'UN'), ('pending', 'PD'), ('approved', 'AP'), ('denied', 'DN')], default='unsubmitted', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
